from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from app.agents.cultural_dub.agent import CulturalDubAgent
from app.agents.cultural_dub.schemas import (
    CulturalDubResult,
    DubRequest,
    TargetLocale,
    TargetRegister,
)
from app.shared.models.audio import AudioMaster, AudioSegment, TranscriptWord
from dotenv import load_dotenv

load_dotenv()


pytestmark = pytest.mark.integration


BACKEND_DIR = Path(__file__).resolve().parents[3]
OUTPUT_DIR = BACKEND_DIR / "data" / "cultural_dub"


def _build_fake_script() -> AudioMaster:
    """
    Build a small synthetic timestamped transcript.

    No source audio is needed by Cultural Dub: AudioMaster already represents
    the canonical timestamped spoken transcript consumed by the agent.
    The actual target-language speech is generated by the real TTS service.
    """
    segments = [
        AudioSegment(
            segment_id="seg_001",
            start_time=0.0,
            end_time=4.0,
            transcript="What's up, bro? Today we're going to make this super easy.",
            words=[
                TranscriptWord(
                    word="What's",
                    start_time=0.00,
                    end_time=0.35,
                ),
                TranscriptWord(
                    word="up,",
                    start_time=0.35,
                    end_time=0.65,
                ),
                TranscriptWord(
                    word="bro?",
                    start_time=0.65,
                    end_time=1.05,
                ),
                TranscriptWord(
                    word="Today",
                    start_time=1.15,
                    end_time=1.55,
                ),
                TranscriptWord(
                    word="we're",
                    start_time=1.55,
                    end_time=1.85,
                ),
                TranscriptWord(
                    word="going",
                    start_time=1.85,
                    end_time=2.15,
                ),
                TranscriptWord(
                    word="to",
                    start_time=2.15,
                    end_time=2.35,
                ),
                TranscriptWord(
                    word="make",
                    start_time=2.35,
                    end_time=2.65,
                ),
                TranscriptWord(
                    word="this",
                    start_time=2.65,
                    end_time=2.85,
                ),
                TranscriptWord(
                    word="super",
                    start_time=2.85,
                    end_time=3.10,
                ),
                TranscriptWord(
                    word="easy.",
                    start_time=3.10,
                    end_time=3.50,
                ),
            ],
        ),
        AudioSegment(
            segment_id="seg_002",
            start_time=4.0,
            end_time=8.0,
            transcript="That hack is actually fire, and the comments were going crazy.",
            words=[
                TranscriptWord(
                    word="That",
                    start_time=4.00,
                    end_time=4.25,
                ),
                TranscriptWord(
                    word="hack",
                    start_time=4.25,
                    end_time=4.55,
                ),
                TranscriptWord(
                    word="is",
                    start_time=4.55,
                    end_time=4.70,
                ),
                TranscriptWord(
                    word="actually",
                    start_time=4.70,
                    end_time=5.10,
                ),
                TranscriptWord(
                    word="fire,",
                    start_time=5.10,
                    end_time=5.45,
                ),
                TranscriptWord(
                    word="and",
                    start_time=5.55,
                    end_time=5.75,
                ),
                TranscriptWord(
                    word="the",
                    start_time=5.75,
                    end_time=5.90,
                ),
                TranscriptWord(
                    word="comments",
                    start_time=5.90,
                    end_time=6.35,
                ),
                TranscriptWord(
                    word="were",
                    start_time=6.35,
                    end_time=6.55,
                ),
                TranscriptWord(
                    word="going",
                    start_time=6.55,
                    end_time=6.85,
                ),
                TranscriptWord(
                    word="crazy.",
                    start_time=6.85,
                    end_time=7.35,
                ),
            ],
        ),
        AudioSegment(
            segment_id="seg_003",
            start_time=8.0,
            end_time=12.0,
            transcript="If you try it, let me know what you think in the comments.",
            words=[
                TranscriptWord(
                    word="If",
                    start_time=8.00,
                    end_time=8.15,
                ),
                TranscriptWord(
                    word="you",
                    start_time=8.15,
                    end_time=8.35,
                ),
                TranscriptWord(
                    word="try",
                    start_time=8.35,
                    end_time=8.60,
                ),
                TranscriptWord(
                    word="it,",
                    start_time=8.60,
                    end_time=8.80,
                ),
                TranscriptWord(
                    word="let",
                    start_time=8.90,
                    end_time=9.10,
                ),
                TranscriptWord(
                    word="me",
                    start_time=9.10,
                    end_time=9.25,
                ),
                TranscriptWord(
                    word="know",
                    start_time=9.25,
                    end_time=9.55,
                ),
                TranscriptWord(
                    word="what",
                    start_time=9.55,
                    end_time=9.75,
                ),
                TranscriptWord(
                    word="you",
                    start_time=9.75,
                    end_time=9.95,
                ),
                TranscriptWord(
                    word="think",
                    start_time=9.95,
                    end_time=10.25,
                ),
                TranscriptWord(
                    word="in",
                    start_time=10.25,
                    end_time=10.40,
                ),
                TranscriptWord(
                    word="the",
                    start_time=10.40,
                    end_time=10.55,
                ),
                TranscriptWord(
                    word="comments.",
                    start_time=10.55,
                    end_time=11.10,
                ),
            ],
        ),
    ]

    return AudioMaster(
        duration=12.0,
        sample_rate=24000,
        channels=1,
        segments=segments,
        cleaned=True,
        synced=True,
    )


def _assert_audio_file(path_value: str | None) -> Path:
    assert path_value, "Cultural Dub did not return an audio path."

    path = Path(path_value)
    assert path.exists(), f"Expected generated audio file: {path}"
    assert path.is_file(), f"Expected an audio file, got: {path}"
    assert path.stat().st_size > 0, f"Generated audio file is empty: {path}"

    return path


@pytest.mark.skipif(
    not os.getenv("GEMINI_API_KEY") or not os.getenv("PARALLEL_API_KEY"),
    reason="Live Cultural Dub integration test requires GEMINI_API_KEY and PARALLEL_API_KEY",
)
@pytest.mark.asyncio
async def test_cultural_dub_agent_run_live():
    """
    Exercise the actual CulturalDubAgent.run() end-to-end.

    There are no fake Gemini responses, fake Parallel responses, fake TTS
    responses, or mocked agent methods in this test.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # The agent writes its relative cultural_dub/<locale>/ artifacts from the
    # current working directory. Running from backend/data therefore places
    # the real artifacts in backend/data/cultural_dub/.
    original_cwd = Path.cwd()

    try:
        os.chdir(OUTPUT_DIR.parent)

        request = DubRequest(
            project_id="cultural-dub-live-test",
            audio_master=_build_fake_script(),
            target_locales=[
                TargetLocale(
                    language="Hindi",
                    geography="IN",
                )
            ],
            register=TargetRegister.CONVERSATIONAL,
            source_language="English",
            generate_audio=True,
            max_duration_overrun_seconds=0.15,
            creator_voice=False,
        )

        # No dependency injection: this is the real agent and therefore its
        # real Gemini / Parallel / TTS dependencies.
        agent = CulturalDubAgent()

        result = await agent.run(request)

    finally:
        os.chdir(original_cwd)

    assert isinstance(result, CulturalDubResult)
    assert result.tracks, "Cultural Dub returned no locale tracks."

    track = result.tracks[0]
    assert track.language == "Hindi"
    assert track.geography == "IN"
    assert track.segments, "Cultural Dub returned no localized segments."

    audio_path = _assert_audio_file(track.audio_path)

    # The output should contain one localized result for every source segment.
    source_ids = {segment.segment_id for segment in request.audio_master.segments}
    result_ids = {segment.segment_id for segment in track.segments}
    assert result_ids == source_ids

    for segment in track.segments:
        assert segment.localized_text.strip()
        assert segment.language == "Hindi"
        assert segment.geography == "IN"

        if segment.audio_path:
            _assert_audio_file(segment.audio_path)

    # Persist a human-readable integration-test report beside the generated
    # audio. This is not a mocked response; it is the actual run result.
    report_path = OUTPUT_DIR / "live_run_result.json"
    report_path.write_text(
        json.dumps(result.model_dump(mode="json"), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    assert audio_path.parent == OUTPUT_DIR / "Hindi-IN"
    assert report_path.exists()

    print("\n=== CULTURAL DUB LIVE RUN ===")
    print(f"Audio:  {audio_path}")
    print(f"Report: {report_path}")
    print(f"Segments: {len(track.segments)}")
    print(f"Research/localization notes: {len(result.localization_notes)}")
    print(f"Review flags: {len(result.review_flags)}")
    print(f"Degraded reasons: {result.degraded_reasons}")