/* Sample responses shaped exactly like the Pydantic models, used when
   NEXT_PUBLIC_DEMO=1 or when the backend is unreachable and
   NEXT_PUBLIC_DEMO_FALLBACK=1. The UI badges these as sample data. */
export const fixtures = {
  creator_scout: {
    creator_recommendations: [
      { creator_name: "Aarti Menon", platform: "YouTube", niche: "personal finance",
        follower_count: 412000, engagement_rate: 0.048, overall_score: 0.91,
        rationale: "Explainer format, 63% of her audience is 22–30 urban India, and she has covered UPI twice without a sponsor.",
        evidence: ["https://example.com/aarti-channel"] },
      { creator_name: "Dev Bhatia", platform: "Instagram", niche: "fintech",
        follower_count: 188000, engagement_rate: 0.061, overall_score: 0.84,
        rationale: "Highest engagement in the set and already posts credit-score content, but the audience skews 18–24.",
        evidence: ["https://example.com/dev-profile"] },
      { creator_name: "Nikhil Rao", platform: "YouTube", niche: "banking",
        follower_count: 96000, engagement_rate: 0.039, overall_score: 0.66,
        rationale: "On-topic but smaller, and his last three videos were interviews rather than explainers.",
        evidence: ["https://example.com/nikhil"] },
    ],
  },

  script_suggestor: {
    version: 1,
    title: "What a UPI credit line does to your credit score",
    hook: "Everyone is explaining what this feature is. Nobody told you this part.",
    status: "draft",
    full_text: "Everyone is explaining what a UPI credit line is…",
    evidence: ["https://example.com/rbi-guidance", "https://example.com/bureau-reporting"],
    beats: [
      { beat_id: "beat_001", start_time: 0, end_time: 3.2,
        text: "Everyone is explaining what this feature is. Nobody told you this part.",
        purpose: "Hook", visual_intent: "Tight MCU, straight to lens",
        audio_intent: "High energy, no music yet", expression: "brows up, direct" },
      { beat_id: "beat_002", start_time: 3.2, end_time: 14.8,
        text: "A credit line on UPI is still credit. It reports to the bureau every month.",
        purpose: "Set the stakes", visual_intent: "Cut to B-roll of a phone payment",
        audio_intent: "Bed enters under the line", expression: "conversational, half-smile" },
      { beat_id: "beat_003", start_time: 14.8, end_time: 31.0,
        text: "Which means utilisation matters. Spend 90% of a small line and your score drops, even if you pay in full.",
        purpose: "The unused angle", visual_intent: "On-screen number climbing",
        audio_intent: "Bed drops out on 'drops'", expression: "lean in, slower" },
      { beat_id: "beat_004", start_time: 31.0, end_time: 46.5,
        text: "Keep it under thirty percent and it does the opposite — it builds history you did not have.",
        purpose: "The payoff", visual_intent: "Split screen, two outcomes",
        audio_intent: "Bed returns, brighter", expression: "warm, resolving" },
      { beat_id: "beat_005", start_time: 46.5, end_time: 58.0,
        text: "So it is not the feature that helps or hurts you. It is the percentage.",
        purpose: "Close and CTA", visual_intent: "Back to MCU, slow push",
        audio_intent: "Bed out on the last word", expression: "direct, settled" },
    ],
  },

  storyboard: {
    version: 1,
    visual_style: "Handheld documentary, warm key against a cool wall, no staged setups.",
    color_palette: "Deep blue, warm amber accent, aged cream for text",
    evidence: ["https://example.com/reference-a"],
    shots: [
      { shot_id: "shot_01", beat_id: "beat_001", start_time: 0, end_time: 3.2,
        shot_type: "Medium close-up", camera_angle: "Eye level, 5° off-axis",
        camera_movement: "Static", framing: "Eyes on the upper third",
        subject: "You, holding the phone at chest height", background: "Desk wall, lamp at frame right",
        lighting: "Soft key camera-left, white card as fill",
        visual_description: "Dead frontal reads as a webcam, so sit slightly off-axis.",
        colour_palette: ["#1B2A3A", "#E8703A"], mood: "Direct, conspiratorial",
        on_screen_text: "Nobody told you this" },
      { shot_id: "shot_02", beat_id: "beat_002", start_time: 3.2, end_time: 14.8,
        shot_type: "Insert", camera_angle: "High, looking down at the phone",
        camera_movement: "Slow push", framing: "Phone fills two thirds",
        subject: "A payment completing", background: "Countertop, out of focus",
        lighting: "Same key, bounce from the counter",
        visual_description: "Shoot this after the main take, same lighting, no relight.",
        colour_palette: ["#1B2A3A", "#F2E8D5"], mood: "Neutral, procedural", on_screen_text: null },
      { shot_id: "shot_03", beat_id: "beat_003", start_time: 14.8, end_time: 31.0,
        shot_type: "Medium close-up", camera_angle: "Eye level",
        camera_movement: "Static", framing: "Slightly tighter than shot 01",
        subject: "You, leaning in", background: "Same wall, lamp dimmed",
        lighting: "Key pulled 30cm closer for contrast",
        visual_description: "The tighter frame carries the turn in the argument.",
        colour_palette: ["#12202E", "#E8703A"], mood: "Serious", on_screen_text: "30%" },
    ],
  },

  audio: {
    file_path: "/outputs/fintech_explainer_v3/master.wav",
    duration: 58.0,
    sample_rate: 24000,
    channels: 1,
    cleaned: true,
    synced: false,
    segments: [
      { segment_id: "beat_001", start_time: 0, end_time: 3.2,
        transcript: "Everyone is explaining what this feature is. Nobody told you this part.",
        words: [
          { word: "Everyone", start_time: 0.04, end_time: 0.51 },
          { word: "is", start_time: 0.51, end_time: 0.63 },
          { word: "explaining", start_time: 0.63, end_time: 1.24 },
        ] },
      { segment_id: "beat_002", start_time: 3.2, end_time: 14.8,
        transcript: "A credit line on UPI is still credit. It reports to the bureau every month.",
        words: [] },
      { segment_id: "beat_003", start_time: 14.8, end_time: 31.0,
        transcript: "Which means utilisation matters.", words: [] },
    ],
  },

  syncer: {
    status: "complete",
    global_offset: 1.84,
    drift_detected: true,
    drift_rate: 0.0004,
    fallback_used: false,
    notes: [
      "Alignment is derived from matched speech, so it is accurate to the word, not the frame.",
      "phone_b_0007.mp4 is variable frame rate — conform before applying any offset.",
    ],
    segments: [
      { segment_id: "cam_a_0001.mov", video_start: 0, video_end: 291.7,
        audio_start: 14.2, audio_end: 305.9, offset: 1.84, confidence: 0.96,
        recommended_take: null },
      { segment_id: "cam_a_0002.mov", video_start: 0, video_end: 222.3,
        audio_start: 320.1, audio_end: 542.4, offset: 2.11, confidence: 0.88,
        recommended_take: "Drifts ~80ms over 3m40s. Split at the halfway point and re-align." },
      { segment_id: "phone_b_0007.mp4", video_start: 0, video_end: 46.0,
        audio_start: 0, audio_end: 0, offset: 0, confidence: 0.21,
        recommended_take: "On-board audio too wind-affected to transcribe. Align on the hand gesture at 02:14." },
    ],
  },

  cultural_dub: {
    dub_tracks: [
      { language: "Hindi", geography: "IN",
        audio_path: "/outputs/fintech_explainer_v3/dub/hi-IN.wav",
        subtitle_path: "/outputs/fintech_explainer_v3/dub/hi-IN.srt",
        segments: [
          { segment_id: "beat_001",
            source_text: "Nobody told you this part.",
            localized_text: "ये वाली बात कोई नहीं बताता।",
            cultural_notes: ["Kept the conspiratorial register rather than the literal phrasing."] },
          { segment_id: "beat_003",
            source_text: "Spend 90% of a small line and your score drops.",
            localized_text: "छोटी लिमिट का 90% खर्च किया, तो स्कोर गिरेगा।",
            cultural_notes: ["'Limit' retained as an English loanword — it is what people actually say."] },
        ] },
    ],
  },

  compliance: {
    status: "passed_with_conditions",
    stage: "script",
    pass_number: 2,
    structural_errors: [],
    degraded_reasons: ["Parallel Extract not enabled; verdicts rest on search excerpts only."],
    issues: [
      { issue_id: "clr_001", label: "Direct comparison to a named competitor",
        kind: "brand", severity: "yellow",
        description: "Comparative advertising is legal in India but the claim has to be substantiable.",
        recommended_action: "Keep the comparison only if you can cite the published rate.",
        substitutes: [], evidence: [{ claim: "ASCI guidance on comparative claims", url: "https://example.com/asci" }] },
      { issue_id: "clr_002", label: "\u201cGuaranteed 90-point jump in 60 days\u201d",
        kind: "claim", severity: "red",
        description: "An unsubstantiated financial outcome inside a sponsored script.",
        recommended_action: "Remove the guarantee.",
        substitutes: ["Rephrase as a range with the bureau's own published guidance behind it."],
        evidence: [{ claim: "Bureau scoring is not deterministic", url: "https://example.com/bureau" }] },
      { issue_id: "clr_003", label: "Disclosure at 0:02", kind: "disclosure", severity: "green",
        description: "Present and upfront, as required.", recommended_action: null,
        substitutes: [], evidence: [] },
    ],
  },
};
